DELETE http://localhost:3001/api/blogs/6626aa931645a2e8a23dc2aa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2kzIiwiaWQiOiI2NjI2MzJmNWQ4MjQ4MDBlYTM2YjY0OGUiLCJpYXQiOjE3MTM3ODAwNDh9.bPrcuE2O_xc8eNnSA1fRWWChfFNOoBv7SqnzHOKIqWc