POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NjI3NjVkNDlmMjEwZmRhZDE0ZTAzYWQiLCJpYXQiOjE3MTM4NTgwNDN9.eR2Foe5ySauUWFIwDkzXJI6JbksWPeNfFF-YC04zNE4

{
    "title": "testuser blog",
    "author": "testuser blog",
    "url": "http://blog.cleancoder.com/",
    "likes": 12

 }